# **TP2 - Bivariate Analysis**

<b>Exploratory Data Analysis & Unsupervised Learning</b><br>
**Course: Dr. HAS Sothea** <br> 
**TP: Ms. UANN Sreyvi**

-------

**Objective**: To equip you all with the skills to analyze and interpret the relationship between two variables. You will explore these relationships as a function of time using the [`Gapminder`](https://pypi.org/project/gapminder/) dataset.

---------

> **The `Jupyter Notebook` for this TP can be downloaded here: [TP2-Bivariate-Gapminder](https://hassothea.github.io/I5_EDA_ITC/TPs/TP2_Bivariate_Analysis.ipynb)**.

-------

In [28]:
# Useful packages for Bivariate Analysis
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import plotly.express as px
import plotly.io as pio
import jinja2
pio.renderers.default = 'notebook'

#%pip install gapminder           # This is for installing the package
from gapminder import gapminder

print(f"* Gapminder dataset loaded: {gapminder.shape[0]} rows, {gapminder.shape[1]} columns")
print(f"* Years covered: {sorted(gapminder['year'].unique())}")
gapminder.head()

* Gapminder dataset loaded: 1704 rows, 6 columns
* Years covered: [np.int64(1952), np.int64(1957), np.int64(1962), np.int64(1967), np.int64(1972), np.int64(1977), np.int64(1982), np.int64(1987), np.int64(1992), np.int64(1997), np.int64(2002), np.int64(2007)]

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

# **1. Pearson and Spearman's correlations**

**a.** Compute Pearson correlation matrix of the three quantitative variables on year $1952$, $1987$ and then $2007$ using `pd.corr()`. Give a brief intuition of the relationship between these variables.

In [29]:
data1952 = gapminder[gapminder['year'] == 1952]
data1987 = gapminder[gapminder['year'] == 1987]
data2007 = gapminder[gapminder['year'] == 2007]

In [30]:
quan_vars = ['lifeExp', 'gdpPercap', 'pop']

data1952 = gapminder[gapminder['year'] == 1952]

data1952[quan_vars].corr()

            lifeExp  gdpPercap       pop
lifeExp    1.000000   0.278024 -0.002725
gdpPercap  0.278024   1.000000 -0.025260
pop       -0.002725  -0.025260  1.000000

In [31]:
# 1.a Pearson correlation matrix for 1952, 1987, and 2007
years = [1952, 1987, 2007]
quant_cols = ['lifeExp', 'pop', 'gdpPercap']

for yr in years:
    sub_df = gapminder[gapminder['year'] == yr][quant_cols]
    corr_pearson = sub_df.corr(method='pearson')
    print(f"=== Pearson Correlation Matrix ({yr}) ===")
    display(corr_pearson.round(4))
    print()

=== Pearson Correlation Matrix (1952) ===

           lifeExp     pop  gdpPercap
lifeExp     1.0000 -0.0027     0.2780
pop        -0.0027  1.0000    -0.0253
gdpPercap   0.2780 -0.0253     1.0000

=== Pearson Correlation Matrix (1987) ===

           lifeExp     pop  gdpPercap
lifeExp     1.0000  0.0331     0.7499
pop         0.0331  1.0000    -0.0517
gdpPercap   0.7499 -0.0517     1.0000

=== Pearson Correlation Matrix (2007) ===

           lifeExp     pop  gdpPercap
lifeExp     1.0000  0.0476     0.6787
pop         0.0476  1.0000    -0.0557
gdpPercap   0.6787 -0.0557     1.0000

In [33]:
%pip install jinja2

Requirement already satisfied: jinja2 in c:\Users\Sreynich\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\Sreynich\AppData\Local\Programs\Python\Python311\Lib\site-packages (from jinja2) (2.1.5)
Note: you may need to restart the kernel to use updated packages.

In [35]:
import sys
print(sys.executable)

import jinja2
print(jinja2.__version__)
print(jinja2.__file__)

c:\Users\Sreynich\AppData\Local\Programs\Python\Python311\python.exe
3.1.3
c:\Users\Sreynich\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\__init__.py

In [36]:
import pandas as pd
import importlib.util

print("Pandas version:", pd.__version__)
print("Jinja2 detected:", importlib.util.find_spec("jinja2"))

try:
    from pandas.io.formats.style import Styler
    print("Pandas Styler imported successfully!")
except Exception as e:
    print(type(e).__name__, e)

Pandas version: 3.0.3
Jinja2 detected: ModuleSpec(name='jinja2', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000021C66DA2B50>, origin='c:\\Users\\Sreynich\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\jinja2\\__init__.py', submodule_search_locations=['c:\\Users\\Sreynich\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\jinja2'])
ImportError Pandas requires version '3.1.5' or newer of 'jinja2' (version '3.1.3' currently installed).

In [39]:
import jinja2
import pandas as pd
import sys

print("Python:", sys.executable)
print("Pandas version:", pd.__version__)
print("Jinja2 version:", jinja2.__version__)
print("Jinja2 location:", jinja2.__file__)

Python: c:\Users\Sreynich\AppData\Local\Programs\Python\Python311\python.exe
Pandas version: 3.0.3
Jinja2 version: 3.1.3
Jinja2 location: c:\Users\Sreynich\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\__init__.py

In [ ]:

print(jinja2.__version__)

In [40]:
import sys
!{sys.executable} -m pip install --upgrade "Jinja2>=3.1.5"

Collecting Jinja2>=3.1.5
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\Sreynich\AppData\Local\Programs\Python\Python311\Lib\site-packages (from Jinja2>=3.1.5) (2.1.5)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Installing collected packages: Jinja2
  Attempting uninstall: Jinja2
    Found existing installation: Jinja2 3.1.3
    Uninstalling Jinja2-3.1.3:
      Successfully uninstalled Jinja2-3.1.3
Successfully installed Jinja2-3.1.6

In [41]:
quan_vars = ['lifeExp', 'gdpPercap', 'pop']
data1952[quan_vars].corr().style.background_gradient(cmap='cool')

AttributeError: The '.style' accessor requires jinja2

> ### **Description & Intuition (Pearson Correlation)**:
> 
> **Pearson's Correlation Coefficient ($r$)** measures the strength and direction of a **linear relationship** between two continuous variables:
> $$r = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum (x_i - \bar{x})^2 \sum (y_i - \bar{y})^2}}$$
> 
> **Intuition from the Matrices**:
> 1. **`lifeExp` vs. `gdpPercap` (Health & Wealth)**:
>    - **1952**: $r = 0.278$ (Moderate positive linear correlation).
>    - **1987**: $r = 0.750$ (Strong positive linear correlation).
>    - **2007**: $r = 0.679$ (Strong positive linear correlation).
>    - *Intuition*: Higher GDP per capita allows governments and citizens to afford superior healthcare, infrastructure, clean drinking water, and nutrition, increasing life expectancy. The correlation dramatically increased after 1952.
> 
> 2. **`pop` vs. `lifeExp` & `pop` vs. `gdpPercap` (Demographics vs. Health/Wealth)**:
>    - Across all three years, the correlation is virtually zero ($r \approx -0.003$ to $0.048$ with `lifeExp`; $r \approx -0.025$ to $-0.056$ with `gdpPercap`).
>    - *Intuition*: A country's sheer population size has **no linear relationship** with its living standards or life expectancy. Highly populated countries include both wealthy developed giants (USA) and developing nations (India, China), while small-population nations range from very rich (Norway, Luxembourg, Kuwait) to very poor.

-----

**b.** Compute Spearman's Rank Correlation of the previous columns in 1952, 1987 and 2007. What do you observe?

In [ ]:
# 1.b Spearman's Rank Correlation for 1952, 1987, and 2007
for yr in years:
    sub_df = gapminder[gapminder['year'] == yr][quant_cols]
    corr_spearman = sub_df.corr(method='spearman')
    print(f"=== Spearman Rank Correlation Matrix ({yr}) ===")
    display(corr_spearman.round(4))
    print()

> ### **What Do You Observe? (Pearson vs. Spearman)**:
> 
> Comparing `lifeExp` vs `gdpPercap` side-by-side:
> - **1952**: Pearson $r = 0.278$ vs. **Spearman $\rho = 0.769$** ($+0.491$ difference!).
> - **1987**: Pearson $r = 0.750$ vs. **Spearman $\rho = 0.892$** ($+0.142$ difference).
> - **2007**: Pearson $r = 0.679$ vs. **Spearman $\rho = 0.857$** ($+0.178$ difference).
> 
> **Why is Spearman's correlation substantially higher than Pearson's, especially in 1952?**
> 1. **Spearman evaluates Monotonicity, Pearson evaluates Linearity**:
>    - Pearson tests whether points lie along a straight line ($y = ax + b$).
>    - Spearman ranks the values ($rank(x)$ vs. $rank(y)$) and evaluates whether $y$ increases whenever $x$ increases, regardless of whether the curve is linear or concave.
> 2. **Non-linear Relationship (The Preston Curve)**:
>    - The true relationship between income and life expectancy is **logarithmic** (diminishing marginal returns): going from \$500 to \$5,000 saves millions of lives; going from \$30,000 to \$35,000 yields only modest longevity gains.
> 3. **Immunity to Outliers**:
>    - Pearson is severely dragged down by extreme outliers in raw dollars (e.g. Kuwait in 1952). Spearman converts raw dollars into ranks ($1, 2, ..., 142$), completely neutralizing the leverage of extreme numerical outliers!

-----

**c.** From the previous result, pick the most interesting pair of variables and plot a graph illustrating their relationship on each year, using proper axis scaling and title.

In [ ]:

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create three subplots, one for each year
fig = make_subplots(
    rows=1,
    cols=3,
    subplot_titles=[
        "GDP (log) vs Life Expectancy (1952)",
        "GDP (log) vs Life Expectancy (1987)",
        "GDP (log) vs Life Expectancy (2007)"
    ]
)

# Add scatterplot for 1952
fig.add_trace(
    go.Scatter(
        x=data1952["gdpPercap"],
        y=data1952["lifeExp"],
        mode="markers",
        name="Year 1952",
        marker=dict(size=6, color="blue")
    ),
    row=1,
    col=1
)

# Add scatterplot for 1987
fig.add_trace(
    go.Scatter(
        x=data1987["gdpPercap"],
        y=data1987["lifeExp"],
        mode="markers",
        name="Year 1987",
        marker=dict(size=6, color="green")
    ),
    row=1,
    col=2
)

# Add scatterplot for 2007
fig.add_trace(
    go.Scatter(
        x=data2007["gdpPercap"],
        y=data2007["lifeExp"],
        mode="markers",
        name="Year 2007",
        marker=dict(size=6, color="purple")
    ),
    row=1,
    col=3
)

# Update overall figure layout
fig.update_layout(
    width=1200,
    height=500,
    title_text="GDP per Capita vs Life Expectancy (1952–2007)",
    showlegend=False
)

# Use logarithmic scale for all three GDP axes
fig.update_xaxes(type="log", title_text="GDP per Capita", row=1, col=1)
fig.update_xaxes(type="log", title_text="GDP per Capita", row=1, col=2)
fig.update_xaxes(type="log", title_text="GDP per Capita", row=1, col=3)
fig.update_yaxes(title_text="Life Expectancy (years)", row=1, col=1)

# Label the y-axes
fig.update_yaxes(title_text="Life Expectancy (years)", row=1, col=1)
fig.update_yaxes(title_text="Life Expectancy (years)", row=1, col=2)
fig.update_yaxes(title_text="Life Expectancy (years)", row=1, col=3)

# Display the graph
fig.show()

In [ ]:
# 1.c Plotting GDP per Capita vs. Life Expectancy across 1952, 1987, and 2007
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Relationship Between GDP per Capita (Log Scale) and Life Expectancy', fontsize=15, fontweight='bold')

for i, yr in enumerate(years):
    sub_df = gapminder[gapminder['year'] == yr]
    
    # Scatter plot with log-scaled x-axis and regression trendline
    sns.regplot(
        data=sub_df,
        x='gdpPercap',
        y='lifeExp',
        logx=True,
        ax=axes[i],
        scatter_kws={'alpha': 0.7, 'color': '#2b5c8f'},
        line_kws={'color': '#d95f02', 'linewidth': 2}
    )
    axes[i].set_xscale('log')
    axes[i].set_title(f'Year {yr} (Spearman rho = {sub_df["lifeExp"].corr(sub_df["gdpPercap"], method="spearman"):.2f})', fontweight='bold')
    axes[i].set_xlabel('GDP per Capita in USD (Logarithmic Scale)')
    axes[i].set_ylabel('Life Expectancy (years)')
    axes[i].grid(True, which="both", ls="--", alpha=0.4)
    axes[i].set_ylim(25, 88)

plt.tight_layout()
plt.show()

-----

**d.** Revisit your intuition of the correlation matrix in year 1952 from question **(a)**, can you see why we observed such a (poor) correlation in 1952?!

In [ ]:
# Investigating the 1952 anomaly: The Kuwait Outlier
df1952 = gapminder[gapminder['year'] == 1952].copy()
top_gdp_1952 = df1952.sort_values(by='gdpPercap', ascending=False).head(5)

print("=== Top 5 Richest Countries in 1952 ===")
display(top_gdp_1952[['country', 'continent', 'gdpPercap', 'lifeExp', 'pop']])

# Correlation with Kuwait vs. without Kuwait
r_with = df1952['lifeExp'].corr(df1952['gdpPercap'], method='pearson')
df1952_no_kuwait = df1952[df1952['country'] != 'Kuwait']
r_without = df1952_no_kuwait['lifeExp'].corr(df1952_no_kuwait['gdpPercap'], method='pearson')

print(f"\n* 1952 Pearson r WITH Kuwait:    {r_with:.4f}")
print(f"* 1952 Pearson r WITHOUT Kuwait: {r_without:.4f}  (nearly DOUBLED!)")
print(f"* 1952 Pearson r on log(gdpPercap): {np.log(df1952['gdpPercap']).corr(df1952['lifeExp']):.4f}")

> ### **Why was the Pearson correlation so poor in 1952?**
> 
> **The Kuwait Oil Outlier!**
> 1. In **1952**, **Kuwait** had an astronomical GDP per capita of **\$108,382** due to early commercial oil discovery paired with a tiny population (~160,000 citizens).
> 2. The second richest country was Switzerland at only \$14,734—meaning Kuwait's GDP per capita was over **7 times higher** than the next wealthiest country!
> 3. Despite immense oil revenues, Kuwait's life expectancy in 1952 was only **55.57 years** (as modern healthcare infrastructure was only beginning to develop).
> 4. In a linear regression ($r$), this single point sits at the far extreme right of the plot ($x = 108,382$) with moderate $y = 55.6$. It acts as an **extreme leverage point**, pulling the entire linear regression line downward and flattening its slope!
> 5. Removing Kuwait alone causes the Pearson correlation in 1952 to leap from **$0.278$ to $0.531$**! Furthermore, applying a logarithmic transformation ($\log(\text{gdpPercap})$) raises the correlation to **$0.78$**.

> **Remark:** Pearson correlation matrix can summarize linear relationship between pairs of quantitative variables but it might be inaccurate and influenced by:
> - **Outliers** (extreme leverage points like Kuwait in 1952)
> - **Non-linearity** (logarithmic returns like the Preston Curve)
> - **Small sample size**
> - **Confounding (causal) variables** (continental healthcare infrastructure, geographical factors)

**Conclusion:** 
When analyzing variables that exhibit exponential growth or diminishing marginal returns (such as wealth vs. health), **Spearman's rank correlation** or **logarithmic transformations** provide a much truer and more robust representation of the underlying relationship than raw Pearson correlation.

# **2. Visualization with more information**

`Scatterplot` is the primary graphic type for visualizing the relationship between two quantitative variables. Additionally, you can include other factors of interest using color, shape, size, facets, etc., depending on the type of those variables. 

------------

The following questions apply to the years 1952, 1987, and 2007:

**a.** Do you think health conditions and economies differ across continents? Compute some indicators to illustrate this.

In [ ]:
# 2.a Indicators across continents in 1952, 1987, and 2007
for yr in years:
    sub = gapminder[gapminder['year'] == yr]
    summary_continent = sub.groupby('continent').agg(
        n_countries=('country', 'count'),
        lifeExp_mean=('lifeExp', 'mean'),
        lifeExp_std=('lifeExp', 'std'),
        lifeExp_median=('lifeExp', 'median'),
        gdp_mean=('gdpPercap', 'mean'),
        gdp_median=('gdpPercap', 'median')
    ).round(2)
    print(f"=== Continental Indicators for Year {yr} ===")
    display(summary_continent)
    print()

In [ ]:
# Visualizing continental distributions with Boxplots in 2007
fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle('Health and Economic Disparities Across Continents (Year 2007)', fontsize=15, fontweight='bold')

sns.boxplot(data=gapminder[gapminder['year'] == 2007], x='continent', y='lifeExp', palette='Set2', ax=axes[0])
axes[0].set_title('Life Expectancy by Continent (2007)', fontweight='bold')
axes[0].set_ylabel('Life Expectancy (years)')

sns.boxplot(data=gapminder[gapminder['year'] == 2007], x='continent', y='gdpPercap', palette='Set2', ax=axes[1])
axes[1].set_title('GDP per Capita by Continent (2007)', fontweight='bold')
axes[1].set_ylabel('GDP per Capita (USD)')

plt.tight_layout()
plt.show()

> ### **Description of Continental Disparities**:
> - **Health (`lifeExp`)**: 
>   - There are massive continental divides. In 2007, **Oceania** (median 80.7 yrs) and **Europe** (median 76.7 yrs) lead the world with low internal variation.
>   - **Africa** lags far behind with a median of only **52.9 years** and high spread ($std = 9.6$ years).
>   - **Asia** spans a wide spectrum, containing both world-leading nations (Japan: 82.6 yrs) and developing nations (Afghanistan: 43.8 yrs).
> - **Economy (`gdpPercap`)**:
>   - Europe and Oceania exhibit high median incomes (>\$25,000), while Africa's median is only **\$1,452**.
>   - The boxes and medians do not overlap between Africa and Europe/Oceania, showing that geography/continent is strongly associated with socioeconomic development.

-----

**c.** We will try to confirm this using Analysis of Variance (ANOVA). 

In 2007,

- Perform one way ANOVA on `lifeExp` and `continent` (you can use `f_oneway` from `scipy.stats` module).

In [ ]:
# One-way ANOVA: lifeExp across continents in 2007
df2007 = gapminder[gapminder['year'] == 2007]

groups_lifeExp = [group['lifeExp'].values for name, group in df2007.groupby('continent')]
f_stat_life, p_val_life = stats.f_oneway(*groups_lifeExp)

print(f"=== One-Way ANOVA: `lifeExp` across continents (2007) ===")
print(f"F-statistic: {f_stat_life:.4f}")
print(f"p-value:     {p_val_life:.4e}")
if p_val_life < 0.05:
    print("Conclusion: Reject H0! There are statistically significant differences in mean life expectancy across continents.")

- Do the same with `gdpPercap` and `continent`.

In [ ]:
# One-way ANOVA: gdpPercap across continents in 2007
groups_gdp = [group['gdpPercap'].values for name, group in df2007.groupby('continent')]
f_stat_gdp, p_val_gdp = stats.f_oneway(*groups_gdp)

print(f"=== One-Way ANOVA: `gdpPercap` across continents (2007) ===")
print(f"F-statistic: {f_stat_gdp:.4f}")
print(f"p-value:     {p_val_gdp:.4e}")
if p_val_gdp < 0.05:
    print("Conclusion: Reject H0! There are statistically significant differences in mean GDP per capita across continents.")

In [ ]:
# Checking ANOVA Assumptions for Year 2007:
print("--- 1. Testing Homoscedasticity (Levene's Test for Equal Variances) ---")
lev_life = stats.levene(*groups_lifeExp)
lev_gdp = stats.levene(*groups_gdp)
print(f"lifeExp Levene test:  W = {lev_life.statistic:.4f}, p-value = {lev_life.pvalue:.4e} (Equal variances rejected!)")
print(f"gdpPercap Levene test: W = {lev_gdp.statistic:.4f}, p-value = {lev_gdp.pvalue:.4e} (Equal variances rejected!)")

print("\n--- 2. Testing Normality within Continents (Shapiro-Wilk Test) ---")
for cont, group in df2007.groupby('continent'):
    if len(group) >= 3:
        sh_life = stats.shapiro(group['lifeExp'])
        sh_gdp = stats.shapiro(group['gdpPercap'])
        print(f"{cont:10s} | lifeExp p={sh_life.pvalue:.4f} | gdpPercap p={sh_gdp.pvalue:.4e}")

- Are these results reliable? Why?

> **Your response**:
> **No, the classical One-Way ANOVA results are NOT strictly reliable.**
> 
> **Why?** One-Way ANOVA requires three foundational mathematical assumptions:
> 1. **Homoscedasticity (Homogeneity of Variances)**: All groups must have approximately equal variances ($\sigma_1^2 = \sigma_2^2 = ... = \sigma_k^2$).
>    - *Levene's test* yields $p = 4.9 	imes 10^{-5}$ for `lifeExp` and $p = 4.3 	imes 10^{-5}$ for `gdpPercap`, **severely rejecting equal variances**.
> 2. **Normality of Residuals**: The values within each continental group should be normally distributed.
>    - *Shapiro-Wilk tests* show significant departures from normality for almost all continents (e.g. GDP per capita in Africa has $p = 7.4 	imes 10^{-9}$ due to extreme skewness).
> 3. **Unequal Group Sizes**: Group sizes are highly unbalanced (Africa: 52, Americas: 25, Asia: 33, Europe: 30, Oceania: 2). When sample sizes and variances are both unequal, the classical $F$-test is sensitive to Type I and Type II errors.

- Propose ideas that might solve this problem or an alternative method.

> **Your response**:
> 1. **Logarithmic Transformation**: Apply a $\log$ transformation to `gdpPercap` ($\log_{10}(\text{gdpPercap})$). This dramatically reduces right-skewness, compresses outliers, and stabilizes group variances.
> 2. **Non-parametric Test (Kruskal-Wallis $H$-test)**: Use `scipy.stats.kruskal`, which evaluates differences in group ranks rather than means and requires **neither normality nor homoscedasticity**.
> 3. **Welch's ANOVA**: An adjusted ANOVA that explicitly relaxes the assumption of equal variances across groups.

In [ ]:
# Solution 1: Non-parametric Kruskal-Wallis H-test
kw_life = stats.kruskal(*groups_lifeExp)
kw_gdp = stats.kruskal(*groups_gdp)

print("=== Alternative: Kruskal-Wallis H-Test (Non-parametric) ===")
print(f"lifeExp:   H = {kw_life.statistic:.4f}, p-value = {kw_life.pvalue:.4e}")
print(f"gdpPercap: H = {kw_gdp.statistic:.4f}, p-value = {kw_gdp.pvalue:.4e}")
print("Both confirm massive, statistically significant continental differences even without normality!")

# Solution 2: Log transformation of GDP per capita + ANOVA
groups_log_gdp = [np.log10(group['gdpPercap'].values) for name, group in df2007.groupby('continent')]
f_log, p_log = stats.f_oneway(*groups_log_gdp)
print(f"\n=== ANOVA on log10(gdpPercap) ===")
print(f"F-statistic: {f_log:.4f}, p-value: {p_log:.4e}")

-----

**d.** We have previously described the relationship between population and life expectancy or GDP per capita. Now, illustrate the effect of population defining **size** of points according to variable `pop`.

In [ ]:
# 2.d Bubble chart: GDP per capita vs. Life Expectancy with point size = pop and color = continent
fig = px.scatter(
    df2007,
    x='gdpPercap',
    y='lifeExp',
    size='pop',
    color='continent',
    hover_name='country',
    log_x=True,
    size_max=60,
    title='Gapminder Bubble Chart (2007): Health vs. Wealth by Continent and Population',
    labels={'gdpPercap': 'GDP per Capita (USD, Log Scale)', 'lifeExp': 'Life Expectancy (years)'},
    template='plotly_white',
    width=900,
    height=550
)
fig.show()

-----

**e.** Now, directly visualize the relation between `pop` and `lifeExp`, then the relation between `pop` and `gdpPercap`. Explain the resulting graphs.

In [ ]:
# 2.e Direct visualization: pop vs. lifeExp and pop vs. gdpPercap
fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle('Direct Relationship of Population with Life Expectancy and GDP per Capita (Year 2007)', fontsize=14, fontweight='bold')

# pop vs lifeExp (log scale for pop)
sns.scatterplot(data=df2007, x='pop', y='lifeExp', hue='continent', s=70, ax=axes[0])
axes[0].set_xscale('log')
axes[0].set_title('Population vs. Life Expectancy', fontweight='bold')
axes[0].set_xlabel('Population (Log Scale)')
axes[0].set_ylabel('Life Expectancy (years)')
axes[0].grid(True, which="both", ls="--", alpha=0.4)

# pop vs gdpPercap (log scale for both)
sns.scatterplot(data=df2007, x='pop', y='gdpPercap', hue='continent', s=70, ax=axes[1])
axes[1].set_xscale('log')
axes[1].set_yscale('log')
axes[1].set_title('Population vs. GDP per Capita', fontweight='bold')
axes[1].set_xlabel('Population (Log Scale)')
axes[1].set_ylabel('GDP per Capita (USD, Log Scale)')
axes[1].grid(True, which="both", ls="--", alpha=0.4)

plt.tight_layout()
plt.show()

> ### **Explanation of Graphs (Population vs. Health & Wealth)**:
> 
> 1. **Distribution Shape**: Both scatter plots show a **horizontal cloud of points with virtually zero trend/slope**.
> 2. **Independence from Demographics**:
>    - Countries with small populations ($< 10$ million) exist across every possible level of life expectancy (from 40 years to 82 years) and wealth (from \$300 to \$45,000).
>    - The demographic giants (China and India, at $>1$ billion) sit right in the middle-income and middle-to-high life expectancy band.
> 3. **Conclusion**:
>    - **Population size does not determine a nation's prosperity or public health.** Instead, economic productivity, governance, institutional stability, and access to medical technology are the true determinants.

# **3. Quantitative vs Qualitative**

**a.** We have seen how life expectancy and economy vary across continents in 2007 ([Slide 25 of the course](https://hassothea.github.io/EDA_ITC/Slides/Bivariate_Analysis.html#/quan.-vs-qual.-3)). Compute $\eta$-squared correlation between `continent` and `lifeExp`, then `continent` with `gdpPercap` in 1952, 1987 and 2007. 

- Do you find the results reasonable?

In [ ]:
# 3.a Compute Eta-squared (correlation ratio) for continent vs. lifeExp and gdpPercap
def compute_eta_squared(df, categorical_col, numerical_col):
    """
    Computes Eta-squared (eta^2) = SS_between / SS_total
    """
    grand_mean = df[numerical_col].mean()
    ss_total = ((df[numerical_col] - grand_mean) ** 2).sum()
    
    group_stats = df.groupby(categorical_col)[numerical_col].agg(['count', 'mean'])
    ss_between = (group_stats['count'] * (group_stats['mean'] - grand_mean) ** 2).sum()
    
    return ss_between / ss_total

eta_results = []
for yr in [1952, 1987, 2007]:
    sub = gapminder[gapminder['year'] == yr]
    eta_life = compute_eta_squared(sub, 'continent', 'lifeExp')
    eta_gdp = compute_eta_squared(sub, 'continent', 'gdpPercap')
    eta_results.append({
        'Year': yr,
        'eta^2 (continent vs. lifeExp)': round(eta_life, 4),
        'eta^2 (continent vs. gdpPercap)': round(eta_gdp, 4)
    })

eta_df = pd.DataFrame(eta_results)
print("=== Eta-squared (Correlation Ratio) Summary ===")
display(eta_df)

> ### **Mathematical Definition & Interpretation of $\eta^2$**:
> 
> The **Correlation Ratio ($\eta^2$)** measures the proportion of total variance in a quantitative variable ($Y$) explained by a qualitative grouping variable ($X$):
> $$\eta^2 = \frac{SS_{\text{between}}}{SS_{\text{total}}} = \frac{\sum_{k} n_k (\bar{y}_k - \bar{y})^2}{\sum_{i} (y_i - \bar{y})^2}$$
> - Benchmark scale: $\eta^2 = 0.01$ (small effect), $\eta^2 = 0.06$ (medium effect), $\eta^2 \ge 0.14$ (large effect).
> 
> ### **Are the results reasonable?**
> **Yes, completely reasonable and insightful!**
> 1. **`continent` vs. `lifeExp`**:
>    - $\eta^2 \approx 0.650$ (1952), $0.592$ (1987), and $0.635$ (2007).
>    - This indicates that **around 60% to 65% of the global variation in life expectancy is explained solely by which continent a country belongs to!** Geographical healthcare disparities and systemic regional living standards create persistent continental clusters.
> 2. **`continent` vs. `gdpPercap`**:
>    - In **1952**: $\eta^2 = 0.048$ (very small!).
>      *Reason*: The oil outlier Kuwait was located in Asia with \$108,000+ GDP/capita, creating massive *within-continent* variance in Asia that completely dwarfed between-continent differences!
>    - In **1987 & 2007**: $\eta^2$ jumped to **$0.471$ and $0.424$** (large effect!).
>      *Reason*: As world economies diversified and global industrialization polarized Europe/Oceania vs. Africa/Asia, continental grouping became a powerful explanatory factor explaining over 42% of economic variance.

# **4. Time evolution**

**a.** Draw the evolution of the following correlations from 1952 to 2007:

- `Pearson` and `Spearman` correlation between life expectancy and GDP per capita
- $\eta$-squared coefficients of continent vs life expectancy, and continents vs GDP per capita.

> Hint: the following figure is expected.

In [ ]:
# 4.a Evolution of all 4 correlation metrics from 1952 to 2007
time_records = []
all_years = sorted(gapminder['year'].unique())

for yr in all_years:
    sub = gapminder[gapminder['year'] == yr]
    r_pearson = sub['lifeExp'].corr(sub['gdpPercap'], method='pearson')
    r_spearman = sub['lifeExp'].corr(sub['gdpPercap'], method='spearman')
    eta_life = compute_eta_squared(sub, 'continent', 'lifeExp')
    eta_gdp = compute_eta_squared(sub, 'continent', 'gdpPercap')
    
    time_records.append({
        'year': yr,
        'Pearson (lifeExp ~ gdpPercap)': r_pearson,
        'Spearman (lifeExp ~ gdpPercap)': r_spearman,
        'eta2 (continent ~ lifeExp)': eta_life,
        'eta2 (continent ~ gdpPercap)': eta_gdp
    })

evol_df = pd.DataFrame(time_records)

# Plotting with Matplotlib & Seaborn
plt.figure(figsize=(12, 6))
plt.plot(evol_df['year'], evol_df['Pearson (lifeExp ~ gdpPercap)'], marker='o', linewidth=2.5, label='Pearson (lifeExp ~ gdpPercap)', color='#1f77b4')
plt.plot(evol_df['year'], evol_df['Spearman (lifeExp ~ gdpPercap)'], marker='s', linewidth=2.5, label='Spearman (lifeExp ~ gdpPercap)', color='#2ca02c')
plt.plot(evol_df['year'], evol_df['eta2 (continent ~ lifeExp)'], marker='^', linewidth=2.5, label=r'$\eta^2$ (continent ~ lifeExp)', color='#ff7f0e')
plt.plot(evol_df['year'], evol_df['eta2 (continent ~ gdpPercap)'], marker='d', linewidth=2.5, label=r'$\eta^2$ (continent ~ gdpPercap)', color='#d62728')

plt.title('Evolution of Bivariate Correlation Metrics (1952 - 2007)', fontsize=15, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('Correlation / Association Coefficient', fontsize=12)
plt.xticks(all_years, rotation=45)
plt.ylim(0, 1.0)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(fontsize=11, loc='center right')
plt.tight_layout()
plt.show()

-----

**b.** Compare side by side the three aspects: population, life expectancy and GDP per Capita between Cambodia and Thailand from 1952 to 2007.

In [ ]:
# 4.b Side-by-side comparison: Cambodia vs. Thailand (1952 - 2007)
cam_thai_df = gapminder[gapminder['country'].isin(['Cambodia', 'Thailand'])].copy()

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Side-by-Side Comparison: Cambodia vs. Thailand (1952 - 2007)', fontsize=16, fontweight='bold')

variables_to_compare = [
    ('pop', 'Population (count)', 'Population Growth'),
    ('lifeExp', 'Life Expectancy (years)', 'Life Expectancy (Health)'),
    ('gdpPercap', 'GDP per Capita (USD)', 'GDP per Capita (Economy)')
]

for idx, (var, ylabel, title) in enumerate(variables_to_compare):
    sns.lineplot(
        data=cam_thai_df,
        x='year',
        y=var,
        hue='country',
        style='country',
        markers=True,
        dashes=False,
        linewidth=3,
        palette={'Cambodia': '#e41a1c', 'Thailand': '#377eb8'},
        ax=axes[idx]
    )
    axes[idx].set_title(title, fontweight='bold')
    axes[idx].set_ylabel(ylabel)
    axes[idx].set_xlabel('Year')
    axes[idx].grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

-----

**c.** Describe what you observed: the world from 1952 to 2007.

> ### **Synthesis: What We Observed About the World from 1952 to 2007**:
> 
> 1. **Global Health Convergence (The Preston Curve Shift)**:
>    - Across the globe, **life expectancy rose dramatically** from an average of ~49 years in 1952 to over ~67 years in 2007.
>    - Importantly, the curve between GDP per capita and life expectancy shifted **upward over time**: even poor countries in 2007 achieved higher life expectancy than countries with identical wealth in 1952, thanks to the global diffusion of vaccines, oral rehydration therapy, clean water infrastructure, and antibiotics.
> 
> 2. **Economic Divergence**:
>    - While health converged, **economic inequality widened**. North America, Western Europe, and Oceania experienced explosive GDP per capita growth, while Sub-Saharan Africa remained stagnant near the poverty line.
>    - $\eta^2$ for continent vs. GDP per capita surged from $\approx 0.05$ to $> 0.42$, confirming that global wealth became starkly divided along continental lines.
> 
> 3. **The Rise of Asia**:
>    - Asia transformed from a continent where over 80% of countries were "unhealthy" in 1952 to an economic and health powerhouse by 2007, led by Japan, South Korea, Taiwan, Singapore, and the massive demographic and economic ascent of China and India.
> 
> 4. **Tragedy and Resilience (Cambodia vs. Thailand)**:
>    - Thailand pursued peaceful industrialization and tourism, achieving steady, uninterrupted growth in health (reaching 70.6 yrs) and wealth (>\$7,400).
>    - Cambodia suffered devastating historical rupture during the 1970s Khmer Rouge genocide, where life expectancy plunged to an unprecedented 31.2 years in 1977. However, the post-1980 era demonstrated astonishing human resilience, with life expectancy recovering back to ~60 years by 2007 and economic growth rekindling.

# Further readings
- Gapminder documentation: [https://www.gapminder.org/data/documentation/](https://www.gapminder.org/data/documentation/)
- A short demonstration video is available here: [Hans Rosling's 200 Countries, 200 Years, 4 Minutes - The Joy of Stats - BBC Four](https://youtu.be/jbkSRLYSojo?si=qipg08VIi999hEgo).
- Graphical tools:
    - [`matplotlib`](https://matplotlib.org/stable/index.html)
    - [`seaborn`](https://seaborn.pydata.org/)
    - [`plotly`](https://plotly.com/python/)